export component Main inherits Window {
    title: "Ye Olde Translator";
    preferred-width: 1280px;
    preferred-height: 720px;
    background: #191919;

    // Divider
    Rectangle {
        x: root.width/2 - 2px;
        y: root.width / 100;
        width: 4px;
        height: root.height - root.width/50;
        background: #333333;
    }

    // Input text area
    Rectangle {
        x: root.width / 100;
        y: root.width / 100;
        width: root.width/2 - root.width/50;
        height: root.height - root.width/50;
        background: #222222;
    }
    // Output text area
    Rectangle {
        x: root.width/2 + root.width / 100;
        y: root.width / 100;
        width: root.width/2 - root.width/50;
        height: root.height - root.width/50;
        background: #222222;
    }
}